### ISSUE TITLE
Issue with deployment to Github Pages

### ISSUE THREAD

**Issue by samfreund** [HENRYMARTIN5/Ethereal#1]
I believe you accidentally tried to deploy this to pages.  This *bugs* me, since none of this would be anything that pages would typically use.

**Comment by HENRYMARTIN5** [comment]
jeez ok then how do you suggest i host it?

**Comment by HENRYMARTIN5** [comment]
I have fixed the issue and have changed deployment to replit instead of github pages, and added an easy deploy button
