### ISSUE TITLE
Stupid Windows

### ISSUE THREAD

**Issue by samfreund** [HENRYMARTIN5/Ethereal#2]
I have an issue.  I suppose that's what this is for, but that's not the point.  The point is that you made this game for *windows*!  How could you!  What about the poor people who only use the superior system, linux, and can't play windows games?  Are you really trying to add to their pain?  You horrible person.

**Comment by HENRYMARTIN5** [comment]
look im sorry but unity refused to run on my riced arch machine so i built for windows

sue me (linux builds coming soon)
